# Generated by Django 3.2 on 2022-06-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_read', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='fullname',
        ),
    ]
